@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.kawaiicakes.chemistrycraft.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;