@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.kawaiicakes.chemistrycraft.compat.jei;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;