@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.kawaiicakes.chemistrycraft.init.registry.block;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;