@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.kawaiicakes.chemistrycraft.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;